export const PUSH_OPERATION_REDOSTACK = "PUSH_OPERATION_REDOSTACK";
export const SHIFT_OPERATION_REDOSTACK = "SHIFT_OPERATION_REDOSTACK";
export const POP_OPERATION_REDOSTACK = "POP_OPERATION_REDOSTACK";
export const CLEAR_OPERATION_REDOSTACK = "CLEAR_OPERATION_REDOSTACK"