export const INIT_ELEMENT = "INIT_ELEMENT";
export const UPDATE_ELEMENT_BY_IDX = "UPDATE_ELEMENT_BY_IDX";
export const ADD_ELEMENT = "ADD_ELEMENT";
export const DELETE_ELEMENT_BY_IDX = "DELETE_ELEMENT_BY_IDX";
