export const PUSH_OPERATION_UNDOSTACK = "PUSH_OPERATION_UNDOSTACK";
export const SHIFT_OPERATION_UNDOSTACK = "SHIFT_OPERATION_UNDOSTACK";
export const POP_OPERATION_UNDOSTACK = "POP_OPERATION_UNDOSTACK";
export const CLEAR_OPERATION_UNDOSTACK = "CLEAR_OPERATION_UNDOSTACK"